/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.co.blits.TugasIkhlas.View;

import id.co.blits.TugasIkhlas.Util.KoneksiDatabase;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author samsung
 */
public class InputPembelian extends javax.swing.JFrame {
    
    KoneksiDatabase con = new KoneksiDatabase();

    /**
     * Creates new form InputPembelian
     */
    public InputPembelian() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldKembali = new javax.swing.JTextField();
        jTextFieldPembeli = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButtonProses = new javax.swing.JButton();
        jTextFieldPesawat = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTotBay = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldHarga = new javax.swing.JTextField();
        jTextFieldBayar = new javax.swing.JTextField();
        jButtonSimpan = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldJumlahA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonBayar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("Jumlah Tiket");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 218, -1, -1));

        jTextFieldKembali.setEditable(false);
        jTextFieldKembali.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jTextFieldKembali.setForeground(new java.awt.Color(0, 153, 153));
        jTextFieldKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 430, 177, -1));

        jTextFieldPembeli.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jTextFieldPembeli.setForeground(new java.awt.Color(0, 153, 153));
        jTextFieldPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPembeliActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 91, 416, -1));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("Harga Tiket");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 176, -1, -1));

        jButtonProses.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonProses.setForeground(new java.awt.Color(0, 153, 153));
        jButtonProses.setText("PROSES");
        jButtonProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProsesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonProses, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 259, -1, -1));

        jTextFieldPesawat.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jTextFieldPesawat.setForeground(new java.awt.Color(0, 153, 153));
        jTextFieldPesawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesawatActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPesawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 133, 177, -1));

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 153));
        jLabel14.setText("Kembali");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 431, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Nama Pesawat");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 134, -1, -1));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 153));
        jLabel12.setText("Total Bayar");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 307, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("PENJUALAN TIKET PESAWAT");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 11, -1, -1));

        jTextFieldTotBay.setEditable(false);
        jTextFieldTotBay.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jTextFieldTotBay.setForeground(new java.awt.Color(0, 153, 153));
        jTextFieldTotBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotBayActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTotBay, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 306, 177, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Nomor Penerbangan");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 134, -1, -1));

        jTextFieldHarga.setEditable(false);
        jTextFieldHarga.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jTextFieldHarga.setForeground(new java.awt.Color(0, 153, 153));
        jTextFieldHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHargaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 175, 138, -1));

        jTextFieldBayar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jTextFieldBayar.setForeground(new java.awt.Color(0, 153, 153));
        jTextFieldBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBayarActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 348, 177, -1));

        jButtonSimpan.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonSimpan.setForeground(new java.awt.Color(0, 153, 153));
        jButtonSimpan.setText("SIMPAN");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 472, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 153, 153));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GA755", "AA455", "LA221", "SA534" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 133, 79, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("--------------------------------");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 153));
        jLabel13.setText("Bayar");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 349, -1, -1));

        jTextFieldJumlahA.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jTextFieldJumlahA.setForeground(new java.awt.Color(0, 153, 153));
        jTextFieldJumlahA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldJumlahAActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldJumlahA, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 217, 46, -1));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Jenis Tiket");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 176, -1, -1));

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 153));
        jButton1.setText("TAMPIL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 472, -1, -1));

        jButtonBayar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonBayar.setForeground(new java.awt.Color(0, 153, 153));
        jButtonBayar.setText("BAYAR");
        jButtonBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBayarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 383, -1, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Nama Pembeli");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 92, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(0, 153, 153));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dewasa", "Anak-anak" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 175, 118, -1));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -170, -1, 240));

        jLabel15.setForeground(new java.awt.Color(0, 153, 153));
        jLabel15.setIcon(new javax.swing.ImageIcon("G:\\New folder\\8885593-c2.jpg")); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 650, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKembaliActionPerformed

    private void jTextFieldPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPembeliActionPerformed

    private void jButtonProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProsesActionPerformed
        // TODO add your handling code here:
        double harga = Double.parseDouble(jTextFieldHarga.getText());
        double jumlah = Double.parseDouble(jTextFieldJumlahA.getText());

        double totbay = harga * jumlah;

        jTextFieldTotBay.setText(""+totbay);
    }//GEN-LAST:event_jButtonProsesActionPerformed

    private void jTextFieldPesawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesawatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesawatActionPerformed

    private void jTextFieldTotBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotBayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotBayActionPerformed

    private void jTextFieldHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHargaActionPerformed

    private void jTextFieldBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBayarActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        // TODO add your handling code here:
        String pembeli = jTextFieldPembeli.getText();
        String pesawat = jTextFieldPesawat.getText();
        double harga = Double.parseDouble(jTextFieldHarga.getText());
        double jumlah = Double.parseDouble(jTextFieldJumlahA.getText());
        double totbay = Double.parseDouble(jTextFieldTotBay.getText());
        con.koneksiDB();
        
        try {
                        String query = "insert into tb_pesawat(namapembeli,namapesawat,totalbayar,hargatiket,jumlahtiket)"
            + " values('"+pembeli+"','"+pesawat+"','"+totbay+"','"+harga+"','"+jumlah+"')";
            con.state.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan..");
            jTextFieldBayar.setText(null);
            jTextFieldHarga.setText(null);
            jTextFieldJumlahA.setText(null);
            jTextFieldKembali.setText(null);
            jTextFieldPembeli.setText(null);
            jTextFieldPesawat.setText(null);
            jTextFieldTotBay.setText(null);

        } catch (SQLException ex) {
            System.err.println("SQLException:"+ex.getMessage());
        }
        
               

        
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String pesawat = null;
        if (jComboBox1.getSelectedItem()== "GA755"){
            pesawat= "Garuda Air";
        }if (jComboBox1.getSelectedItem()== "AA455"){
            pesawat = "Asia Air";
        }if (jComboBox1.getSelectedItem() == "LA221")
        pesawat = "Lion Air";{
        }if (jComboBox1.getSelectedItem()== "SA534")
        pesawat = "Sriwijaya Air";

        jTextFieldPesawat.setText(""+pesawat);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextFieldJumlahAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJumlahAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldJumlahAActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextFieldBayar.setText(null);
        jTextFieldHarga.setText(null);
        jTextFieldJumlahA.setText(null);
        jTextFieldKembali.setText(null);
        jTextFieldPembeli.setText(null);
        jTextFieldPesawat.setText(null);
        jTextFieldTotBay.setText(null); 
        
        TampilPembelian pindah = new TampilPembelian();
        pindah.setVisible(true);
        InputPembelian.this.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBayarActionPerformed
        // TODO add your handling code here:
        double bayar = Double.parseDouble(jTextFieldBayar.getText());
        double totbay = Double.parseDouble(jTextFieldTotBay.getText());

        double kembali = bayar - totbay ;

        jTextFieldKembali.setText(""+kembali);
    }//GEN-LAST:event_jButtonBayarActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        double harga = 0 ;
        String pesawat = jTextFieldPesawat.getText() ;
        if (jComboBox2.getSelectedItem() == "Dewasa" && "Garuda Air".equals(pesawat) )
        harga = 850000;{
        }if (jComboBox2.getSelectedItem() == "Dewasa" && "Asia Air".equals(pesawat) )
        harga = 550000;{
        }if (jComboBox2.getSelectedItem() == "Dewasa" && "Lion Air".equals(pesawat) )
        harga = 500000;{
        }if (jComboBox2.getSelectedItem() == "Dewasa" && "Sriwijaya Air".equals(pesawat) )
        harga = 525000;{
        }if (jComboBox2.getSelectedItem() == "Anak-anak" && "Garuda Air".equals(pesawat) )
        harga = 500000;{
        }if (jComboBox2.getSelectedItem() == "Anak-anak" && "Asia Air".equals(pesawat) )
        harga = 400000;{
        }if (jComboBox2.getSelectedItem() == "Anak-anak" && "Lion Air".equals(pesawat) )
        harga = 375000;{
        }if (jComboBox2.getSelectedItem() == "Anak-anak" && "Sriwijaya Air".equals(pesawat) )
        harga = 350000;{
        }

        jTextFieldHarga.setText(""+harga);
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputPembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBayar;
    private javax.swing.JButton jButtonProses;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldBayar;
    private javax.swing.JTextField jTextFieldHarga;
    private javax.swing.JTextField jTextFieldJumlahA;
    private javax.swing.JTextField jTextFieldKembali;
    private javax.swing.JTextField jTextFieldPembeli;
    private javax.swing.JTextField jTextFieldPesawat;
    private javax.swing.JTextField jTextFieldTotBay;
    // End of variables declaration//GEN-END:variables
}
