/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.co.blits.TugasIkhlas.View;

import id.co.blits.TugasIkhlas.Util.KoneksiDatabase;
import java.sql.ResultSet;
import java.sql.SQLDataException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samsung
 */
public class TampilPembelian extends javax.swing.JFrame {

    KoneksiDatabase con = new KoneksiDatabase();
    
    
    
    public TampilPembelian()  { 
        initComponents();
        setLocationRelativeTo(null);
        con.koneksiDB();
        datatable();
    }
    
    private void datatable()  {
        DefaultTableModel tabel = new DefaultTableModel();
        
        tabel.addColumn("Id");
        tabel.addColumn("Nama Pembeli");
        tabel.addColumn("Nama Pesawat");
        tabel.addColumn("Harga Tiket");
        tabel.addColumn("Jumlah Tiket");
        tabel.addColumn("Total Bayar");
        
        jTable1.setModel(tabel);
        
        try {
            String sql = "select * from tb_pesawat";
            
            ResultSet res = con.state.executeQuery(sql);
            while(res.next()){
                tabel.addRow(new Object[]{
                    res.getString("no"),
                    res.getString("namapembeli"),
                    res.getString("namapesawat"),
                    res.getString("hargatiket"),
                    res.getString("jumlahtiket"),
                    res.getString("totalbayar")
                        
                } );
            
            
                jTable1.setModel(tabel);
            }
        } catch (Exception e) {
            System.err.println("SQLException:"+e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButtonEdit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonHapus = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButtonBaru = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField6.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(0, 153, 153));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 161, 190, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("No");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Total Bayar");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 162, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 153, 153));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 11, 31, -1));

        jButtonEdit.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonEdit.setForeground(new java.awt.Color(0, 153, 153));
        jButtonEdit.setText("EDIT");
        jButtonEdit.setEnabled(false);
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 203, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Nama Pembeli");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 42, -1, -1));

        jButtonHapus.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonHapus.setForeground(new java.awt.Color(0, 153, 153));
        jButtonHapus.setText("HAPUS");
        jButtonHapus.setEnabled(false);
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 203, -1, -1));

        jTextField2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 153, 153));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 41, 190, -1));

        jButtonBaru.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonBaru.setForeground(new java.awt.Color(0, 153, 153));
        jButtonBaru.setText("BARU");
        jButtonBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBaruActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 203, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Nama Pesawat");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, -1, -1));

        jScrollPane2.setForeground(new java.awt.Color(0, 153, 153));

        jTable1.setForeground(new java.awt.Color(0, 153, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 375, 90));

        jTextField3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 153, 153));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 71, 190, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Harga Tiket");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 102, -1, -1));

        jTextField4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(0, 153, 153));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 101, 190, -1));

        jTextField5.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(0, 153, 153));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 131, 190, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Jumlah Tiket");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 132, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("G:\\New folder\\8896725-mug-cup-clock.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 0, 620, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        // TODO add your handling code here:
        int pilih = JOptionPane.showConfirmDialog(null, "Yakin Anda Ingin Hapus?","",JOptionPane.YES_NO_OPTION);
        if (pilih == JOptionPane.YES_NO_OPTION){
        String no = jTextField1.getText();
            try {
               String kueriHapus = "delete from tb_pesawat where no='"+no+"'";
            con.state.executeUpdate(kueriHapus);
           
           JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus..");
           datatable(); 
            } 
            catch (SQLException ex) {
                System.err.println("Error : "+ex);
            }
        }  
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
        String no = jTextField1.getText();
        String pembeli = jTextField2.getText();
        String pesawat = jTextField3.getText();
        String harga = jTextField4.getText();
        String jumlah = jTextField5.getText();
        String totalbayar = jTextField6.getText();   
        
        try {
                        con.koneksiDB();
            String kueriEdit = "update tb_pesawat set "
                    + "namapembeli ='"+pembeli+"', namapesawat ='"+pesawat+"', hargatiket='"+harga+"', jumlahtiket='"+jumlah+"', totalbayar='"+totalbayar+"'where no='"+no+"'";
            
           con.state.executeUpdate(kueriEdit);
            
            JOptionPane.showMessageDialog(null, "Data Berhasil di ubah");
            datatable();

        } catch (SQLException ex) {
        Logger.getLogger(TampilPembelian.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

                int table = jTable1.getSelectedRow();
        //mengambil data dari table
        String ambilNo = jTable1.getValueAt(table, 0).toString();
        String ambilPembeli = jTable1.getValueAt(table, 1).toString();
        String ambilPesawat = jTable1.getValueAt(table, 2).toString();
        String ambilHarga = jTable1.getValueAt(table, 3).toString();
        String ambilJumlah = jTable1.getValueAt(table, 4).toString();
        String ambilTotalBayar = jTable1.getValueAt(table, 5).toString();
    
        jTextField1.setText(ambilNo);
        jTextField2.setText(ambilPembeli);
        jTextField3.setText(ambilPesawat);
        jTextField4.setText(ambilHarga);
        jTextField5.setText(ambilJumlah);
        jTextField6.setText(ambilTotalBayar);
        
        jButtonEdit.setEnabled(true);
        jButtonHapus.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBaruActionPerformed
        // TODO add your handling code here:
        InputPembelian pindah = new InputPembelian();
        pindah.setVisible(true);
        TampilPembelian.this.setVisible(false);
        
    }//GEN-LAST:event_jButtonBaruActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilPembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBaru;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
